PROSPECT_TYPES = {
    "sme_owner": {
        "label": "SME Business Owner / Founder",
        "hot_buttons": ["business survival", "key person risk", "succession planning", "protecting what they built"],
        "services": ["Key Person Insurance", "Business Continuity Planning", "Buy-Sell Agreement Funding", "Estate Planning"],
        "pain_points": [
            "What happens to the business if you or your co-founder can't work?",
            "Is your business protected if a key person leaves or passes away?",
            "Do you have a plan for ownership transition?",
        ],
        "disc_tendency": "D/I",
        "tone": "direct, results-focused, respect their time",
    },
    "md_director": {
        "label": "Managing Director / C-Suite",
        "hot_buttons": ["corporate governance", "talent retention", "risk management", "legacy"],
        "services": ["Group Insurance", "Key Person Insurance", "Estate Planning", "Wealth Planning"],
        "pain_points": [
            "Are your employee benefits competitive enough to retain top talent?",
            "Does your board have a plan for key person risk?",
            "Is your personal wealth structured efficiently alongside your corporate role?",
        ],
        "disc_tendency": "D",
        "tone": "executive-level, strategic, concise",
    },
    "hr_head": {
        "label": "Head of HR / People & Culture",
        "hot_buttons": ["talent retention", "employee welfare", "benefits benchmarking", "compliance"],
        "services": ["Group Insurance", "Employee Benefits", "Corporate Wellness"],
        "pain_points": [
            "Are your employee benefits keeping up with market standards?",
            "How does your group insurance compare to competitors?",
            "Are you confident your coverage actually protects your team?",
        ],
        "disc_tendency": "S/C",
        "tone": "data-backed, collaborative, employee-welfare focused",
    },
    "hnw_individual": {
        "label": "High Net Worth Individual",
        "hot_buttons": ["wealth preservation", "legacy", "tax efficiency", "exclusivity", "privacy"],
        "services": ["Estate Planning", "Trust Structures", "Wealth Planning", "LPA"],
        "pain_points": [
            "Is your wealth truly protected across generations?",
            "Have you structured your estate to minimize disputes?",
            "Does your current advisor integrate business and personal planning?",
        ],
        "disc_tendency": "varies",
        "tone": "sophisticated, premium, understated confidence",
    },
    "special_needs_parent": {
        "label": "Parent / Caregiver of Special Needs Dependant",
        "hot_buttons": ["peace of mind", "long-term care", "child's future", "financial security"],
        "services": ["SNTC Trust Planning", "CPF SNSS", "Insurance & Care Funding", "Letter of Intent"],
        "pain_points": [
            "Who will take care of your child when you're no longer able to?",
            "Is there a financial plan in place for their lifelong care?",
            "Do you know about the SNTC and CPF SNSS options available?",
        ],
        "disc_tendency": "S",
        "tone": "deeply empathetic, gentle, never salesy — lead with care",
    },
    "young_professional": {
        "label": "Young Professional / Early Career",
        "hot_buttons": ["getting started right", "CPF optimization", "building wealth early", "protection gaps"],
        "services": ["Financial Advisory", "Wealth Accumulation", "Risk Management", "CPF Planning"],
        "pain_points": [
            "Are you making the most of your CPF contributions?",
            "Do you have a financial plan beyond just saving?",
            "What happens to your income if you can't work for 6 months?",
        ],
        "disc_tendency": "I/D",
        "tone": "approachable, no jargon, practical, aspirational",
    },
    "referral_warm": {
        "label": "Warm Referral / Mutual Connection",
        "hot_buttons": ["trust transfer", "personal recommendation", "no-pressure conversation"],
        "services": ["depends on referrer context"],
        "pain_points": ["depends on referrer context"],
        "disc_tendency": "varies",
        "tone": "warm, personal, reference the mutual connection naturally",
    },
    "event_attendee": {
        "label": "Workshop / Event Attendee",
        "hot_buttons": ["follow-up on interest", "value from the event", "next step"],
        "services": ["depends on event topic"],
        "pain_points": ["depends on event topic"],
        "disc_tendency": "varies",
        "tone": "friendly follow-up, reference specific event moments, add value",
    },
}

DM_SEQUENCE = {
    "connection_request": {
        "stage": 1,
        "label": "Connection Request Note",
        "max_chars": 300,
        "goal": "Get accepted. No selling. Pure value and relevance.",
        "guidelines": [
            "Reference something specific about them (role, company, post, mutual connection)",
            "State a genuine reason to connect — shared interest, industry, geography",
            "Never pitch in the connection request",
            "Keep it under 300 characters (LinkedIn limit)",
            "End with a soft, natural close",
        ],
    },
    "welcome_dm": {
        "stage": 2,
        "label": "Welcome Message (Day 0-1 after acceptance)",
        "max_chars": 600,
        "goal": "Build rapport. Deliver value. Plant a seed.",
        "guidelines": [
            "Thank them for connecting",
            "Share one genuinely useful insight or resource relevant to their role",
            "Mention what you do in ONE sentence — no pitch",
            "Ask a question that invites conversation (not 'can I help you?')",
            "Use Lusi's Intent Statement approach — take the pressure off",
        ],
    },
    "value_touch_1": {
        "stage": 3,
        "label": "Value Touch #1 (Day 3-5)",
        "max_chars": 800,
        "goal": "Demonstrate expertise. Create curiosity. No ask yet.",
        "guidelines": [
            "Share an insight, article, or observation relevant to their industry/role",
            "Tie it to a pain point they likely face (based on prospect type)",
            "Use consequence framing — hint at the cost of not addressing it",
            "Position yourself as a knowledgeable resource, not a seller",
            "End with a soft question or thought-provoker",
        ],
    },
    "value_touch_2": {
        "stage": 4,
        "label": "Value Touch #2 (Day 7-10)",
        "max_chars": 800,
        "goal": "Deepen the relationship. Transition toward a conversation.",
        "guidelines": [
            "Reference something they posted or commented on (if possible)",
            "Share a brief case study or anonymised client story relevant to them",
            "Use NEPQ Problem Awareness approach — ask about their current situation",
            "Introduce the idea of a no-obligation conversation naturally",
            "Apply DISC-appropriate language",
        ],
    },
    "soft_ask": {
        "stage": 5,
        "label": "Soft Ask (Day 12-15)",
        "max_chars": 600,
        "goal": "Invite a conversation. Permission-based. No pressure.",
        "guidelines": [
            "Summarise the value you've shared so far (briefly)",
            "Use Lusi's Intent Statement: 'not here to sell, just to explore if there's a fit'",
            "Make the ask specific: '15-minute call', 'coffee chat', 'quick Zoom'",
            "Give them an easy out — 'If the timing isn't right, no worries at all'",
            "Use assumptive language for the CTA: 'Would Tuesday or Thursday work better?'",
        ],
    },
    "follow_up": {
        "stage": 6,
        "label": "Follow-Up (Day 18-20, if no response to soft ask)",
        "max_chars": 400,
        "goal": "Gentle nudge. Add new value. One more chance.",
        "guidelines": [
            "Don't reference being ignored — keep it light and fresh",
            "Share a new piece of value (article, insight, trend)",
            "Restate the offer briefly",
            "Apply the 2-Day Rule — this should feel timely, not desperate",
        ],
    },
    "breakup": {
        "stage": 7,
        "label": "Breakup Message (Day 25-30, final attempt)",
        "max_chars": 300,
        "goal": "Close the loop gracefully. Leave the door open.",
        "guidelines": [
            "Acknowledge they're busy — no guilt",
            "Let them know you won't follow up further (removes pressure)",
            "Leave the door open: 'If this ever becomes relevant, I'm here'",
            "Keep it short, dignified, and warm",
            "Often the breakup message gets the highest response rate",
        ],
    },
}

CAMPAIGN_TRIGGERS = [
    "New connection accepted — start welcome sequence",
    "Prospect posted about business challenges — engage on post, then DM",
    "Prospect changed roles/companies — congratulate and reconnect",
    "Regulatory change (CPF, MAS) — share insight with relevant prospects",
    "Workshop/webinar coming up — invite sequence",
    "Year-end planning season — estate planning and review push",
    "Budget season (Q4/Q1) — group insurance renewal conversations",
    "Life event signals (marriage, new child, promotion) — relevant outreach",
]
